export const brokerInformationMock = {
  pathUpdate: '',
  status: 1,
  description: 'CNPJ não está cadastrado',
  information: {
    federalId: '84.948.157/0001-33',
    brokerCompanyName: 'JUNTO SEGUROS S.A.',
    address: 'CURITIBA',
    number: '1440',
    complement: 'ANDAR 15',
    zipCode: '80.410-201',
    bairro: 'CENTRO',
    city: 'CURITIBA',
    state: 'PR',
    email: 'contabil@jmsegs.com',
  },
  bankDetails: {
    name: '',
    bankCode: '',
    accounNumber: '',
    bankNumber: '',
    bankDigit: '',
    accounDigit: '',
  },
  codeIsValid: false,
  susepCode: '',
  iss: 0,
  simplesOptant: false,
  hasProductDamageInsurance: false,
  renewRegistration: false,
  susepSituation: false,
  brokerExternalId: 0,
  brokerUserName: '',
};
