export const registerBrokerDTOMock = {
  address: 'Rua Teste',
  bankName: 0,
  bankNumber: 1,
  branchNumber: 0,
  brokerCompanyName: 'Teste corretor',
  city: 'Curitiba',
  complement: 'teste',
  currentAccountNumber: 0,
  digitalAgencyNumber: 0,
  digitalContactNumber: 0,
  email: '',
  federalId: '91382861000137',
  hasProductDamageInsurance: false,
  iSS: 0,
  number: '181',
  renewRegistration: true,
  simplesOptant: true,
  state: 'RS',
  susepCode: 202034970,
  susepCodeSituation: 1,
  susepSituation: true,
  zipCode: '90.460-190',
  nameResponsable: '',
  cpfResponsable: '',
  phoneNumberResponsable: '',
  emailBroker: '',
};
