export enum ModalityTypeEnum {
  DEFAULT = 'DEFAULT',
  EXECUTANTE_CONSTRUTOR = 'EXECUTANTE_CONSTRUTOR',
  ANTECIPACAO_DE_RECEBIVEIS_CONTRATUAIS = 'ANTECIPACAO_DE_RECEBIVEIS_CONTRATUAIS',
  ADUANEIRO_TRANSITO = 'ADUANEIRO_TRANSITO',
  REGISTRO_ANELL = 'REGISTRO_ANELL',
}
