export enum ModalityTypeEnum {
  DEFAULT = 'DEFAULT',
  EXECUTANTE_CONSTRUTOR = 'EXECUTANTE_CONSTRUTOR',
  ANTECIPACAO_DE_RECEBIVEIS_CONTRATUAIS = 'ANTECIPACAO_DE_RECEBIVEIS_CONTRATUAIS',
  ADUANEIRO_TRANSITO = 'ADUANEIRO_TRANSITO',
  REGISTRO_ANELL = 'REGISTRO_ANELL',
  PARCELAMENTO_ADMINISTRATIVO_FISCAL = 'PARCELAMENTO_ADMINISTRATIVO_FISCAL',
  RETENCAO_DE_PAGAMENTO = 'RETENCAO_DE_PAGAMENTO',
}
