module.exports = {
  projects: [
    '<rootDir>/apps/plataforma',
    '<rootDir>/apps/fidelize',
    '<rootDir>/apps/fidelize-mapeamentos',
    '<rootDir>/apps/vendors',
    '<rootDir>/modules/corretor-emissao',
    '<rootDir>/modules/broker-signup',
    '<rootDir>/modules/fidelize-dashboard',
    '<rootDir>/modules/fidelize-mapeamentos-import',
    '<rootDir>/modules/vendors-proposal',
    '<rootDir>/modules/vendors-authentication',
    '<rootDir>/modules/vendors-policies',
    '<rootDir>/modules/vendors-pre-approval',
    '<rootDir>/libs/infrastructure/http-client',
    '<rootDir>/libs/shared/hooks',
    '<rootDir>/libs/shared/ui',
    '<rootDir>/libs/shared/utils',
    '<rootDir>/libs/services',
  ],
};
