export * from './InsuredDTO';
export * from './InsuredAddressDTO';
export * from './PolicyholderDTO';
export * from './PolicyholderAffiliateDTO';
export * from './ProjectDTO';
export * from './PolicyholderContactDTO';
export * from './ModalityDTO';
export * from './ProposalDTO';
export * from './UpdateProposalStatusDTO';
