export const brokerInformationMock = {
    status: 1,
    description: 'CNPJ não está cadastrado',
    information: {
        cnpj: '84948157000133',
        matriz_filial: '1',
        razao_social: 'JUNTO SEGUROS S.A',
        nome_fantasia: '',
        situacao: '02',
        data_situacao: '20051103',
        motivo_situacao: '00',
        nm_cidade_exterior:'' ,
        cod_pais: '',
        nome_pais: '',
        cod_nat_juridica: '2054',
        data_inicio_ativ: '19920124',
        cnae_fiscal: '6512000',
        tipo_logradouro: 'RUA',
        logradouro: 'VISCONDE DE NACAR',
        numero: '1440',
        complemento: 'ANDAR 15',
        bairro: 'CENTRO',
        cep: '80410201',
        uf: 'PR',
        cod_municipio: '7535',
        municipio: 'CURITIBA',
        ddd_1: '41',
        telefone_1: '32819190',
        ddd_2: '41',
        telefone_2: '32819282',
        ddd_fax: '',
        num_fax: '',
        email: 'CONTABIL@JMSEGS.COM',
        qualif_resp: '16',
        capital_social: '135550644,31',
        porte: '05',
        opc_simples: '',
        data_opc_simples: '',
        data_exc_simples: '',
        opc_mei: '',
        sit_especial: '',
        data_sit_especial: ''
    }
}

