/* eslint-disable camelcase */

export interface CompanyInformationModel {
        federalId: string,
        parentCompany: string,
        corporateName: string,
        fantasyName: string,
        situation: string,
        dateSituation: string,
        reasonSituation: string,
        cityNameForeign: string,
        countryCod: string,
        countryName: string,
        codNatJuridica: string,
        dateStart: string,
        cnaeFiscal: string,
        addressType: string,
        address: string,
        number: string,
        complement: string,
        neighbourhood: string,
        cep: string,
        uf: string,
        municipalityCod: string,
        municipality: string,
        ddd1: string,
        phone1: string,
        ddd2: string,
        phone2: string,
        dddfax: string,
        numberFax: string,
        email: string,
        qualifResp: string,
        shareCapital:string,
        size: string,
        opcSimple: string,
        dateOpcSimple: string,
        dateExcSimple: string,
        opcMei: string,
        specialSituation: string,
        dateSpecialSituation: string
}
