export enum ProposalStatusEnum {
  DEFAULT = -1,
  UNDEFINED = 0,
  IN_PROGRESS = 1,
  ANALYSIS = 2,
  AWAITING_APPROVAL = 3,
  READY_TO_ISSUE = 4,
  ISSUED = 5,
  TO_EXPIRE = 6,
  EXPIRED = 7,
  REFUSED = 8,
  CANCELLED = 9,
  APPROVED = 10,
}
