export const policyholderMock = {
  activity: 'SERVICOS DE COMUNICACAO E DIVERSOES',
  city: 'CURITIBA',
  class: 'BB',
  closingReferenceDay: 0,
  companyName: 'TOMADOR TESTE – SQUAD DESACOPLAMENTO',
  district: 'CENTRO',
  email: '',
  externalId: 180988,
  federalId: '91833813000118',
  hangs: [],
  id: 180988,
  invoiceDueDateDay: 0,
  isNew: false,
  regionalName: 'Regional PR',
  state: 'PR',
  street: 'R VISCONDE DE NÁCAR',
  useBill: true,
  validCredit: false,
  zipCode: '80410201',
};
