export * from './storeMock';
export * from './getComponentMock';
export * from './constantsMock';
export * from './insuredListMock';
export * from './insuredAdressesMock';
export * from './policyholdersMock';
export * from './policyholderAffiliatesMock';
export * from './modalityListMock';
export * from './proposalMock';
